version: '3.9'

services:
  express:
    container_name: express
    build:
      context: ./express
      dockerfile: Dockerfile
      target: production
    restart: always
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DATABASE
    volumes:
      - ./express:/app/express
      - /app/express/node_modules
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - my-network

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./mongodb_data:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongodb_data: